# Retains default and configurable name-values for the integration framework
# Names reference the blockchain that they store information for

networks:
    ethereum_main:
        name: "Ethereum Mainnet"
        url: "wss://eth-mainnet.ws.alchemyapi.io/v2/YR6392nqy3S_PeXCAJC9ihTBESl6iXIs"
        chain_id: 1
        private_keys:
            - 2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
        transaction_limit: 958108
        transaction_timeout: 120000000000
        gas_estimation_buffer: 100000